
#ifndef  __IC3_PLATFORM_CONFIG_INTERNAL_ARCH_ARM64_H__
#define  __IC3_PLATFORM_CONFIG_INTERNAL_ARCH_ARM64_H__

#if !defined( IC3_PCL_MEMORY_BASE_ALIGNMENT )
#  define IC3_PCL_MEMORY_BASE_ALIGNMENT 8
#endif

#define IC3_PCL_ENDIANNESS_NATIVE     IC3_PCL_ENDIANNESS_BE
#define IC3_PCL_ENDIANNESS_NON_NATIVE IC3_PCL_ENDIANNESS_LE
#define IC3_PCL_TARGET_64             1

#endif /*  __IC3_PLATFORM_CONFIG_INTERNAL_ARCH_ARM64_H__ */
