
#ifndef  __IC3_PLATFORM_CONFIG_INTERNAL_ARCH_X86_H__
#define  __IC3_PLATFORM_CONFIG_INTERNAL_ARCH_X86_H__

#if !defined( IC3_PCL_MEMORY_BASE_ALIGNMENT )
#  define IC3_PCL_MEMORY_BASE_ALIGNMENT 4
#endif

#define IC3_PCL_ENDIANNESS_NATIVE     IC3_PCL_ENDIANNESS_LE
#define IC3_PCL_ENDIANNESS_NON_NATIVE IC3_PCL_ENDIANNESS_BE
#define IC3_PCL_TARGET_64             0

#endif /*  __IC3_PLATFORM_CONFIG_INTERNAL_ARCH_X86_H__ */
