
#include "POSIXCommon.h"
#include <cerrno>

namespace Ic3::System
{

	namespace Platform
	{

		const char * PXAQueryErrnoStringByCode( int pErrno )
		{
			switch( pErrno )
			{
			#if( PCL_TARGET_OS & PCL_TARGET_FLAG_OS_APPLE )
				ic3CaseReturn( EPERM           , "Operation not permitted" );
				ic3CaseReturn( ENOENT          , "No such file or directory" );
				ic3CaseReturn( ESRCH           , "No such process" );
				ic3CaseReturn( EINTR           , "Interrupted system call" );
				ic3CaseReturn( EIO             , "Input/output error" );
				ic3CaseReturn( ENXIO           , "No such device or address" );
				ic3CaseReturn( E2BIG           , "Argument list too long" );
				ic3CaseReturn( ENOEXEC         , "Exec format error" );
				ic3CaseReturn( EBADF           , "Bad file descriptor" );
				ic3CaseReturn( ECHILD          , "No child processes" );
				ic3CaseReturn( EDEADLK         , "Resource deadlock avoided" );
				ic3CaseReturn( ENOMEM          , "Cannot allocate memory" );
				ic3CaseReturn( EACCES          , "Permission denied" );
				ic3CaseReturn( EFAULT          , "Bad address" );
				ic3CaseReturn( ENOTBLK         , "Block device required" );
				ic3CaseReturn( EBUSY           , "Device or resource busy" );
				ic3CaseReturn( EEXIST          , "File exists" );
				ic3CaseReturn( EXDEV           , "Invalid cross-device link" );
				ic3CaseReturn( ENODEV          , "No such device" );
				ic3CaseReturn( ENOTDIR         , "Not a directory" );
				ic3CaseReturn( EISDIR          , "Is a directory" );
				ic3CaseReturn( EINVAL          , "Invalid argument" );
				ic3CaseReturn( ENFILE          , "Too many open files in system" );
				ic3CaseReturn( EMFILE          , "Too many open files" );
				ic3CaseReturn( ENOTTY          , "Inappropriate ioctl for device" );
				ic3CaseReturn( ETXTBSY         , "Text file busy" );
				ic3CaseReturn( EFBIG           , "File too large" );
				ic3CaseReturn( ENOSPC          , "No space left on device" );
				ic3CaseReturn( ESPIPE          , "Illegal seek" );
				ic3CaseReturn( EROFS           , "Read-only file system" );
				ic3CaseReturn( EMLINK          , "Too many links" );
				ic3CaseReturn( EPIPE           , "Broken pipe" );
				ic3CaseReturn( EDOM            , "Numerical argument out of domain" );
				ic3CaseReturn( ERANGE          , "Numerical result out of range" );
				ic3CaseReturn( EAGAIN          , "Resource temporarily unavailable" );
				ic3CaseReturn( EINPROGRESS     , "Operation now in progress" );
				ic3CaseReturn( EALREADY        , "Operation already in progress" );
				ic3CaseReturn( ENOTSOCK        , "Socket operation on non-socket */" );
				ic3CaseReturn( EDESTADDRREQ    , "Destination address required */" );
				ic3CaseReturn( EMSGSIZE        , "Message too long */" );
				ic3CaseReturn( EPROTOTYPE      , "Protocol wrong type for socket */" );
				ic3CaseReturn( ENOPROTOOPT     , "Protocol not available */" );
				ic3CaseReturn( EPROTONOSUPPORT , "Protocol not supported */" );
				ic3CaseReturn( ESOCKTNOSUPPORT , "Socket type not supported" );
				ic3CaseReturn( ENOTSUP         , " Operation not supported" );
				ic3CaseReturn( EPFNOSUPPORT    , "Protocol family not supported" );
				ic3CaseReturn( EAFNOSUPPORT    , "Address family not supported by protocol family */" );
				ic3CaseReturn( EADDRINUSE      , "Address already in use */" );
				ic3CaseReturn( EADDRNOTAVAIL   , "Can't assign requested address */" );
				ic3CaseReturn( ENETDOWN        , "Network is down */" );
				ic3CaseReturn( ENETUNREACH     , "Network is unreachable */" );
				ic3CaseReturn( ENETRESET       , "Network dropped connection on reset */" );
				ic3CaseReturn( ECONNABORTED    , "Software caused connection abort */" );
				ic3CaseReturn( ECONNRESET      , "Connection reset by peer */" );
				ic3CaseReturn( ENOBUFS         , "No buffer space available */" );
				ic3CaseReturn( EISCONN         , "Socket is already connected */" );
				ic3CaseReturn( ENOTCONN        , "Socket is not connected */" );
				ic3CaseReturn( ESHUTDOWN       , "Can't send after socket shutdown */" );
				ic3CaseReturn( ETOOMANYREFS    , "Too many references: can't splice */" );
				ic3CaseReturn( ETIMEDOUT       , "Operation timed out */" );
				ic3CaseReturn( ECONNREFUSED    , "Connection refused */" );
				ic3CaseReturn( ELOOP           , "Too many levels of symbolic links */" );
				ic3CaseReturn( ENAMETOOLONG    , "File name too long */" );
				ic3CaseReturn( EHOSTDOWN       , "Host is down */" );
				ic3CaseReturn( EHOSTUNREACH    , "No route to host */" );
				ic3CaseReturn( ENOTEMPTY       , "Directory not empty */" );
				ic3CaseReturn( EPROCLIM        , "Too many processes */" );
				ic3CaseReturn( EUSERS          , "Too many users */" );
				ic3CaseReturn( EDQUOT          , "Disc quota exceeded */" );
				ic3CaseReturn( ESTALE          , "Stale NFS file handle */" );
				ic3CaseReturn( EREMOTE         , "Too many levels of remote in path */" );
				ic3CaseReturn( EBADRPC         , "RPC struct is bad */" );
				ic3CaseReturn( ERPCMISMATCH    , "RPC version wrong */" );
				ic3CaseReturn( EPROGUNAVAIL    , "RPC prog. not avail */" );
				ic3CaseReturn( EPROGMISMATCH   , "Program version wrong */" );
				ic3CaseReturn( EPROCUNAVAIL    , "Bad procedure for program */" );
				ic3CaseReturn( ENOLCK          , "No locks available */" );
				ic3CaseReturn( ENOSYS          , "Function not implemented */" );
				ic3CaseReturn( EFTYPE          , "Inappropriate file type or format */" );
				ic3CaseReturn( EAUTH           , "Authentication error */" );
				ic3CaseReturn( ENEEDAUTH       , "Need authenticator */" );
				ic3CaseReturn( EPWROFF         , "Device power is off */" );
				ic3CaseReturn( EDEVERR         , "Device error, e.g. paper out */" );
				ic3CaseReturn( EOVERFLOW       , "Value too large to be stored in data type */" );
				ic3CaseReturn( EBADEXEC        , "Bad executable */" );
				ic3CaseReturn( EBADARCH        , "Bad CPU type in executable */" );
				ic3CaseReturn( ESHLIBVERS      , "Shared library version mismatch */" );
				ic3CaseReturn( EBADMACHO       , "Malformed Macho file */" );
				ic3CaseReturn( ECANCELED       , "Operation canceled */" );
				ic3CaseReturn( EIDRM           , "Identifier removed */" );
				ic3CaseReturn( ENOMSG          , "No message of desired type */" );
				ic3CaseReturn( EILSEQ          , "Illegal byte sequence */" );
				ic3CaseReturn( ENOATTR         , "Attribute not found */" );
				ic3CaseReturn( EBADMSG         , "Bad message */" );
				ic3CaseReturn( EMULTIHOP       , "Reserved */" );
				ic3CaseReturn( ENODATA         , "No message available on STREAM */" );
				ic3CaseReturn( ENOLINK         , "Reserved */" );
				ic3CaseReturn( ENOSR           , "No STREAM resources */" );
				ic3CaseReturn( ENOSTR          , "Not a STREAM */" );
				ic3CaseReturn( EPROTO          , "Protocol error */" );
				ic3CaseReturn( ETIME           , "STREAM ioctl timeout */" );
				ic3CaseReturn( EOPNOTSUPP      , "Operation not supported on socket */" );
				ic3CaseReturn( ENOPOLICY       , "No such policy registered */" );
				ic3CaseReturn( ENOTRECOVERABLE , "State not recoverable */" );
				ic3CaseReturn( EOWNERDEAD      , "Previous owner died */" );
				ic3CaseReturn( EQFULL          , "Interface output queue is full */" );
			#elif( PCL_TARGET_OS & ( PCL_TARGET_PLATFORM_ANDROID | PCL_TARGET_PLATFORM_LINUX ) )
				ic3CaseReturn( EPERM           , "Operation not permitted" );
				ic3CaseReturn( ENOENT          , "No such file or directory" );
				ic3CaseReturn( ESRCH           , "No such process" );
				ic3CaseReturn( EINTR           , "Interrupted system call" );
				ic3CaseReturn( EIO             , "Input/output error" );
				ic3CaseReturn( ENXIO           , "No such device or address" );
				ic3CaseReturn( E2BIG           , "Argument list too long" );
				ic3CaseReturn( ENOEXEC         , "Exec format error" );
				ic3CaseReturn( EBADF           , "Bad file descriptor" );
				ic3CaseReturn( ECHILD          , "No child processes" );
				ic3CaseReturn( EAGAIN          , "Resource temporarily unavailable" );
				ic3CaseReturn( ENOMEM          , "Cannot allocate memory" );
				ic3CaseReturn( EACCES          , "Permission denied" );
				ic3CaseReturn( EFAULT          , "Bad address" );
				ic3CaseReturn( ENOTBLK         , "Block device required" );
				ic3CaseReturn( EBUSY           , "Device or resource busy" );
				ic3CaseReturn( EEXIST          , "File exists" );
				ic3CaseReturn( EXDEV           , "Invalid cross-device link" );
				ic3CaseReturn( ENODEV          , "No such device" );
				ic3CaseReturn( ENOTDIR         , "Not a directory" );
				ic3CaseReturn( EISDIR          , "Is a directory" );
				ic3CaseReturn( EINVAL          , "Invalid argument" );
				ic3CaseReturn( ENFILE          , "Too many open files in system" );
				ic3CaseReturn( EMFILE          , "Too many open files" );
				ic3CaseReturn( ENOTTY          , "Inappropriate ioctl for device" );
				ic3CaseReturn( ETXTBSY         , "Text file busy" );
				ic3CaseReturn( EFBIG           , "File too large" );
				ic3CaseReturn( ENOSPC          , "No space left on device" );
				ic3CaseReturn( ESPIPE          , "Illegal seek" );
				ic3CaseReturn( EROFS           , "Read-only file system" );
				ic3CaseReturn( EMLINK          , "Too many links" );
				ic3CaseReturn( EPIPE           , "Broken pipe" );
				ic3CaseReturn( EDOM            , "Numerical argument out of domain" );
				ic3CaseReturn( ERANGE          , "Numerical result out of range" );
				ic3CaseReturn( EDEADLOCK       , "Resource deadlock avoided" );
				ic3CaseReturn( ENAMETOOLONG    , "File name too long" );
				ic3CaseReturn( ENOLCK          , "No locks available" );
				ic3CaseReturn( ENOSYS          , "Function not implemented" );
				ic3CaseReturn( ENOTEMPTY       , "Directory not empty" );
				ic3CaseReturn( ELOOP           , "Too many levels of symbolic links" );
				ic3CaseReturn( ENOMSG          , "No message of desired type" );
				ic3CaseReturn( EIDRM           , "Identifier removed" );
				ic3CaseReturn( ECHRNG          , "Channel number out of range" );
				ic3CaseReturn( EL2NSYNC        , "Level 2 not synchronized" );
				ic3CaseReturn( EL3HLT          , "Level 3 halted" );
				ic3CaseReturn( EL3RST          , "Level 3 reset" );
				ic3CaseReturn( ELNRNG          , "Link number out of range" );
				ic3CaseReturn( EUNATCH         , "Protocol driver not attached" );
				ic3CaseReturn( ENOCSI          , "No CSI structure available" );
				ic3CaseReturn( EL2HLT          , "Level 2 halted" );
				ic3CaseReturn( EBADE           , "Invalid exchange" );
				ic3CaseReturn( EBADR           , "Invalid request descriptor" );
				ic3CaseReturn( EXFULL          , "Exchange full" );
				ic3CaseReturn( ENOANO          , "No anode" );
				ic3CaseReturn( EBADRQC         , "Invalid request code" );
				ic3CaseReturn( EBADSLT         , "Invalid slot" );
				ic3CaseReturn( EBFONT          , "Bad font file format" );
				ic3CaseReturn( ENOSTR          , "Device not a stream" );
				ic3CaseReturn( ENODATA         , "No data available" );
				ic3CaseReturn( ETIME           , "Timer expired" );
				ic3CaseReturn( ENOSR           , "Out of streams resources" );
				ic3CaseReturn( ENONET          , "Machine is not on the network" );
				ic3CaseReturn( ENOPKG          , "Package not installed" );
				ic3CaseReturn( EREMOTE         , "Object is remote" );
				ic3CaseReturn( ENOLINK         , "Link has been severed" );
				ic3CaseReturn( EADV            , "Advertise error" );
				ic3CaseReturn( ESRMNT          , "Srmount error" );
				ic3CaseReturn( ECOMM           , "Communication error on send" );
				ic3CaseReturn( EPROTO          , "Protocol error" );
				ic3CaseReturn( EMULTIHOP       , "Multihop attempted" );
				ic3CaseReturn( EDOTDOT         , "RFS specific error" );
				ic3CaseReturn( EBADMSG         , "Bad message" );
				ic3CaseReturn( EOVERFLOW       , "Value too large for defined data type" );
				ic3CaseReturn( ENOTUNIQ        , "Name not unique on network" );
				ic3CaseReturn( EBADFD          , "File descriptor in bad state" );
				ic3CaseReturn( EREMCHG         , "Remote address changed" );
				ic3CaseReturn( ELIBACC         , "Can not access a needed shared library" );
				ic3CaseReturn( ELIBBAD         , "Accessing a corrupted shared library" );
				ic3CaseReturn( ELIBSCN         , ".lib section in a.out corrupted" );
				ic3CaseReturn( ELIBMAX         , "Attempting to link in too many shared libraries" );
				ic3CaseReturn( ELIBEXEC        , "Cannot exec a shared library directly" );
				ic3CaseReturn( EILSEQ          , "Invalid or incomplete multibyte or wide character" );
				ic3CaseReturn( ERESTART        , "Interrupted system call should be restarted" );
				ic3CaseReturn( ESTRPIPE        , "Streams pipe error" );
				ic3CaseReturn( EUSERS          , "Too many users" );
				ic3CaseReturn( ENOTSOCK        , "Socket operation on non-socket" );
				ic3CaseReturn( EDESTADDRREQ    , "Destination address required" );
				ic3CaseReturn( EMSGSIZE        , "Message too long" );
				ic3CaseReturn( EPROTOTYPE      , "Protocol wrong type for socket" );
				ic3CaseReturn( ENOPROTOOPT     , "Protocol not available" );
				ic3CaseReturn( EPROTONOSUPPORT , "Protocol not supported" );
				ic3CaseReturn( ESOCKTNOSUPPORT , "Socket type not supported" );
				ic3CaseReturn( ENOTSUP         , "Operation not supported" );
				ic3CaseReturn( EPFNOSUPPORT    , "Protocol family not supported" );
				ic3CaseReturn( EAFNOSUPPORT    , "Address family not supported by protocol" );
				ic3CaseReturn( EADDRINUSE      , "Address already in use" );
				ic3CaseReturn( EADDRNOTAVAIL   , "Cannot assign requested address" );
				ic3CaseReturn( ENETDOWN        , "Network is down" );
				ic3CaseReturn( ENETUNREACH     , "Network is unreachable" );
				ic3CaseReturn( ENETRESET       , "Network dropped connection on reset" );
				ic3CaseReturn( ECONNABORTED    , "Software caused connection abort" );
				ic3CaseReturn( ECONNRESET      , "Connection reset by peer" );
				ic3CaseReturn( ENOBUFS         , "No buffer space available" );
				ic3CaseReturn( EISCONN         , "Transport endpoint is already connected" );
				ic3CaseReturn( ENOTCONN        , "Transport endpoint is not connected" );
				ic3CaseReturn( ESHUTDOWN       , "Cannot send after transport endpoint shutdown" );
				ic3CaseReturn( ETOOMANYREFS    , "Too many references: cannot splice" );
				ic3CaseReturn( ETIMEDOUT       , "Connection timed out" );
				ic3CaseReturn( ECONNREFUSED    , "Connection refused" );
				ic3CaseReturn( EHOSTDOWN       , "Host is down" );
				ic3CaseReturn( EHOSTUNREACH    , "No route to host" );
				ic3CaseReturn( EALREADY        , "Operation already in progress" );
				ic3CaseReturn( EINPROGRESS     , "Operation now in progress" );
				ic3CaseReturn( ESTALE          , "Stale file handle" );
				ic3CaseReturn( EUCLEAN         , "Structure needs cleaning" );
				ic3CaseReturn( ENOTNAM         , "Not a XENIX named type file" );
				ic3CaseReturn( ENAVAIL         , "No XENIX semaphores available" );
				ic3CaseReturn( EISNAM          , "Is a named type file" );
				ic3CaseReturn( EREMOTEIO       , "Remote I/O error" );
				ic3CaseReturn( EDQUOT          , "Disk quota exceeded" );
				ic3CaseReturn( ENOMEDIUM       , "No medium found" );
				ic3CaseReturn( EMEDIUMTYPE     , "Wrong medium type" );
				ic3CaseReturn( ECANCELED       , "Operation canceled" );
				ic3CaseReturn( ENOKEY          , "Required key not available" );
				ic3CaseReturn( EKEYEXPIRED     , "Key has expired" );
				ic3CaseReturn( EKEYREVOKED     , "Key has been revoked" );
				ic3CaseReturn( EKEYREJECTED    , "Key was rejected by service" );
				ic3CaseReturn( EOWNERDEAD      , "Owner died" );
				ic3CaseReturn( ENOTRECOVERABLE , "State not recoverable" );
				ic3CaseReturn( ERFKILL         , "Operation not possible due to RF-kill" );
				ic3CaseReturn( EHWPOISON       , "Memory page has hardware error" );
			#endif
				default: break;
			}
			return "UNKNOWN_ERROR";
		}

	} // namespace Platform

} // namespace Ic3::System
