
#ifndef __IC3_SYSTEM_PLATFORM_OSAPI_WIN32_ASSET_SYSTEM_H__
#define __IC3_SYSTEM_PLATFORM_OSAPI_WIN32_ASSET_SYSTEM_H__

#include <Ic3/System/Internal/Platform/Common/FileBasedAssetSystem.h>

#endif // __IC3_SYSTEM_PLATFORM_OSAPI_WIN32_ASSET_SYSTEM_H__
