
#pragma once

#ifndef __IC3_GRAPHICS_HW3D_GLC_PREREQUISITES_H__
#define __IC3_GRAPHICS_HW3D_GLC_PREREQUISITES_H__

#include <Ic3/Graphics/GCI/Memory/CommonGPUMemoryDefs.h>
#include <Ic3/System/OpenGLDriver.h>

#define IC3_GX_GL_PLATFORM_TYPE_DESKTOP 0x7100
#define IC3_GX_GL_PLATFORM_TYPE_ES   0x7200

#define IC3_GX_GL_TARGET_GL32 0x8100
#define IC3_GX_GL_TARGET_GL43 0x8200
#define IC3_GX_GL_TARGET_ES31 0x8300

#if( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )
#  define IC3_GX_GL_PLATFORM_TYPE IC3_GX_GL_PLATFORM_TYPE_DESKTOP
#elif( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_ES )
#  define IC3_GX_GL_PLATFORM_TYPE IC3_GX_GL_PLATFORM_TYPE_ES
#else
#  if( !GL_PLATFORM_TYPE_DESKTOP && GL_PLATFORM_TYPE_ES )
#    define IC3_GX_GL_PLATFORM_TYPE IC3_GX_GL_PLATFORM_TYPE_ES
#  elif( GL_PLATFORM_TYPE_DESKTOP )
#    define IC3_GX_GL_PLATFORM_TYPE IC3_GX_GL_PLATFORM_TYPE_DESKTOP
#  else
#    error "Invalid GL Platform Type"
#  endif
#endif

#if ( IC3_GX_GL_PLATFORM_TYPE == IC3_GX_GL_PLATFORM_TYPE_DESKTOP ) && defined( IC3_DRIVER_GRAPHICS_HW3D_GL3_BUILD )
#  define IC3_GX_GL_TARGET IC3_GX_GL_TARGET_GL32
#endif
#if ( IC3_GX_GL_PLATFORM_TYPE == IC3_GX_GL_PLATFORM_TYPE_DESKTOP ) && defined( IC3_DRIVER_GRAPHICS_HW3D_GL4_BUILD )
#  define IC3_GX_GL_TARGET IC3_GX_GL_TARGET_GL43
#endif
#if ( IC3_GX_GL_PLATFORM_TYPE == IC3_GX_GL_PLATFORM_TYPE_ES ) && defined( IC3_DRIVER_GRAPHICS_HW3D_GLES3_BUILD )
#  define IC3_GX_GL_TARGET IC3_GX_GL_TARGET_ES31
#endif

#  define IC3_GX_GL_TARGET IC3_GX_GL_TARGET_GL43

#if !defined( IC3_GX_GL_TARGET )
#  error ""
#endif

#define IC3_GX_GL_FEATURE_SUPPORT_BUFFER_PERSISTENT_MAP \
	( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_GL43 )

#define IC3_GX_GL_FEATURE_SUPPORT_DEBUG_OUTPUT \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_PRIMITIVE_FILL_MODE \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_PRIMITIVE_TYPE_ADJACENCY \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_PRIMITIVE_TYPE_PATCHES \
	( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_GL43 )

#define IC3_GX_GL_FEATURE_SUPPORT_SHADER_PIPELINE_OBJECT \
	( ( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_GL43 ) || ( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_ES31 ) )

#define IC3_GX_GL_FEATURE_SUPPORT_SHADER_TYPE_GEOMETRY \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_SHADER_TYPE_TESSELATION \
	( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_GL43 )

#define IC3_GX_GL_FEATURE_SUPPORT_SHADER_TYPE_COMPUTE \
	( ( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_GL43 ) || ( IC3_GX_GL_TARGET == IC3_GX_GL_TARGET_ES31 ) )

#define IC3_GX_GL_FEATURE_SUPPORT_TEXTURE_ANISOTROPIC_FILTER \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_TEXTURE_EXTENDED_ADDRESS_MODE \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_TEXTURE_FORMAT_BGR \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#define IC3_GX_GL_FEATURE_SUPPORT_TEXTURE_FORMAT_COMPRESSED_BCX \
	( IC3_SYSTEM_GL_PLATFORM_TYPE == IC3_SYSTEM_GL_PLATFORM_TYPE_DESKTOP )

#if( IC3_BUILD_STATIC )
#  define IC3_GX_GL_API
#  define IC3_GX_GL_CLASS
#  define IC3_GX_GL_OBJ    extern
#else
#  if( IC3_DRIVER_GRAPHICS_HW3D_GLC_BUILD )
#    define IC3_GX_GL_API    PCL_ATTR_DLL_EXPORT
#    define IC3_GX_GL_CLASS  PCL_ATTR_DLL_EXPORT
#    define IC3_GX_GL_OBJ    PCL_ATTR_DLL_EXPORT
#  else
#    define IC3_GX_GL_API    PCL_ATTR_DLL_IMPORT
#    define IC3_GX_GL_CLASS  PCL_ATTR_DLL_IMPORT
#    define IC3_GX_GL_OBJ    PCL_ATTR_DLL_IMPORT
#  endif
#endif

#include "Prerequisites/GLCommonDefs.h"
#include "Prerequisites/GLDebugOutput.h"
#include "Prerequisites/GLObject.h"

namespace Ic3::Graphics::GCI
{

	// class RenderPassConfigurationCompiledStateDefault;

	class GLBlendStateDescriptor;
	class GLDepthStencilStateDescriptor;
	class GLRasterizerStateDescriptor;
	class GLGraphicsShaderLinkageDescriptor;
	class GLVertexAttributeLayoutDescriptor;
	class GLRenderTargetBindingCompiledState;
	class GLVertexSourceBindingDescriptor;

	Ic3GCIDeclareClassHandle( GLCommandList );
	Ic3GCIDeclareClassHandle( GLCommandSystem );
	Ic3GCIDeclareClassHandle( GLGPUDevice );
	Ic3GCIDeclareClassHandle( GLGPUDriver );
	Ic3GCIDeclareClassHandle( GLPresentationLayer );

} // namespace Ic3::Graphics::GCI

#endif // __IC3_GRAPHICS_HW3D_GLC_PREREQUISITES_H__
