
#ifndef __IC3_SYSTEM_EVENT_SOURCE_H__
#define __IC3_SYSTEM_EVENT_SOURCE_H__

#include "EventCommon.h"
#include "SysObject.h"

namespace Ic3::System
{

	ic3SysDeclareHandle( EventController );

	class EventSource : public SysObject
	{
		friend class EventController;

	public:
		explicit EventSource( SysContextHandle pSysContext );
		virtual ~EventSource() noexcept;

		IC3_ATTR_NO_DISCARD void * getEventSourceNativeData() const;

		template <typename TOutput>
		IC3_ATTR_NO_DISCARD TOutput * getEventSourceNativeDataAs() const;

        IC3_ATTR_NO_DISCARD EventController * getEventController() const;

        IC3_ATTR_NO_DISCARD EventController & getEventControllerRef() const;

		IC3_ATTR_NO_DISCARD bool isPrimaryEventSource() const;

		IC3_ATTR_NO_DISCARD bool isLastEventSource() const;

	protected:
		virtual void onDestroySystemObjectRequested() override;

		void setEventController( EventControllerHandle pEventController );

		void setEventSourceNativeData( void * pNativeData );

		void resetEventSourceNativeData();

	private:
		// EventController which handles events generated by this source.
		// A single EventSource may be registered only in one controller at any given time.
		// NOTE: this is an active reference, so the controller is always accessible to a source object.
		EventControllerHandle _eventControllerActiveRef = nullptr;

		// Native data of this event source. This is actually a pointer to Platform::EventSourceNativeData,
		// but the whole Platform:: content is by default not visible in the public part of the library.
		// Actual event sources (Window, GLSurface, etc.) set this on construction.
		void * _eventSourceNativeData;
	};

	template <typename TOutput>
	inline TOutput * EventSource::getEventSourceNativeDataAs() const
	{
		return static_cast<TOutput *>( getEventSourceNativeData() );
	}

} // namespace Ic3::System

#endif // __IC3_SYSTEM_EVENT_SOURCE_H__
