
#ifndef __IC3_SYSTEM_PERF_COUNTER_H__
#define __IC3_SYSTEM_PERF_COUNTER_H__

#include "Prerequisites.h"
#include <cppx/chrono.h>

namespace Ic3::System
{

	/// @brief Type used to represent the resolution of a PerfCounter.
	using perf_counter_res_t = uint64;

	/// @brief Type used to represent values of stamps generated by a PerfCounter.
	using perf_counter_value_t = uint64;

	/// @brief
	using perf_counter_ratio_t = std::pair<native_int, native_int>;

	class PerfCounter
	{
	public:
	/// @brief Queries and returns the current value of a system-specific, high-performance clock.
		/// Returned value should not be analysed or interpreted directly by the app - its unit is
		/// platform-specific and my yield number of ticks, nanoseconds or some other type of duration.
		IC3_SYSTEM_API_NODISCARD static perf_counter_value_t QueryCurrentStamp();

		/// @brief Returns the resolution of a counter as a number of units which elapse during a period of one second.
		IC3_SYSTEM_API_NODISCARD static perf_counter_res_t QueryResolution();

		/// @brief Converts a difference between two PC stamps to a duration value using specified unit ratio.
		/// Ratio represents a unit expressed as a fraction relative to a second. I.e. converting to nanoseconds
		/// would be done by calling: ConvertToDuration( timeStampDiff, perf_counter_ratio_t{ 1, 1000000000 } );
		IC3_SYSTEM_API_NODISCARD static long double ConvertToDuration(
				perf_counter_value_t pStampDiff,
				const perf_counter_ratio_t & pUnitRatio );

		/// @brief Converts a duration value back to a PC time stamp difference using specified unit ratio.
		/// Assertion: ConvertFromDuration( ConvertToDuration( timeStampDiff, R ), R ) == timeStampDiff for any given R.
		IC3_SYSTEM_API_NODISCARD static perf_counter_value_t ConvertFromDuration(
				long double pDuration,
				const perf_counter_ratio_t & pUnitRatio );

		/// @brief Helper function which converts a perf counter duration to a duration value in unit expressed as Ic3::EDurationPeriod.
		template <cppx::duration_period tpPeriod>
		IC3_SYSTEM_API_NODISCARD static long double ConvertToDuration( perf_counter_value_t pStampDiff )
		{
			return ConvertToDuration( pStampDiff, cppx::duration_traits<tpPeriod>::unit_ratio );
		}

		/// @brief Helper function which converts a duration value in unit expressed as Ic3::EDurationPeriod back to a PC time stamp difference.
		template <cppx::duration_period tpPeriod>
		IC3_SYSTEM_API_NODISCARD static perf_counter_value_t ConvertFromDuration( const cppx::duration<tpPeriod> & pDuration )
		{
			return ConvertFromDuration( pDuration.count(), cppx::duration_traits<tpPeriod>::unit_ratio );
		}
	};

} // namespace Ic3::System

#endif // __IC3_SYSTEM_PERF_COUNTER_H__
