
#pragma once

#ifndef __IC3_GRAPHICS_HW3D_VKCOMMON_CONSTANTS_MAP_H__
#define __IC3_GRAPHICS_HW3D_VKCOMMON_CONSTANTS_MAP_H__

namespace Ic3::Graphics::GCI
{



}

#endif // __IC3_GRAPHICS_HW3D_VKCOMMON_CONSTANTS_MAP_H__
