
#pragma once

#ifndef __IC3_GRAPHICS_HW3D_GLCOMMON_COMMON_DEFS_H__
#define __IC3_GRAPHICS_HW3D_GLCOMMON_COMMON_DEFS_H__

#define GL_TEX_FORMAT_COMPRESSED_BC1         GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
#define GL_TEX_FORMAT_COMPRESSED_BC1_SRGBA   GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT
#define GL_TEX_FORMAT_COMPRESSED_BC2         GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
#define GL_TEX_FORMAT_COMPRESSED_BC2_SRGB    GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT
#define GL_TEX_FORMAT_COMPRESSED_BC3         GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
#define GL_TEX_FORMAT_COMPRESSED_BC3_SRGB    GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT
#define GL_TEX_FORMAT_COMPRESSED_BC4_SNORM   GL_COMPRESSED_SIGNED_RED_RGTC1
#define GL_TEX_FORMAT_COMPRESSED_BC4_UNORM   GL_COMPRESSED_RED_RGTC1
#define GL_TEX_FORMAT_COMPRESSED_BC5_SNORM   GL_COMPRESSED_SIGNED_RG_RGTC2
#define GL_TEX_FORMAT_COMPRESSED_BC5_UNORM   GL_COMPRESSED_RG_RGTC2
#define GL_TEX_FORMAT_COMPRESSED_BC6H_SFLOAT GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB
#define GL_TEX_FORMAT_COMPRESSED_BC6H_UFLOAT GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_ARB
#define GL_TEX_FORMAT_COMPRESSED_BC7         GL_COMPRESSED_RGBA_BPTC_UNORM_ARB
#define GL_TEX_FORMAT_COMPRESSED_BC7_SRGB    GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB

#define GL_IC3_ERR_INVALID_PARAM ( ( GLenum ) 0xFFFFFFFFu )

namespace Ic3::Graphics::GCI
{

	constexpr GLenum cvGLInvalidValue = QLimits<GLenum>::maxValue;

	constexpr GLuint cvGLInvalidProgramLocation = QLimits<GLuint>::maxValue;

	enum EGLRuntimeSupportFlags : uint32
	{
		E_GL_RUNTIME_SUPPORT_FLAG_BUFFER_IMMUTABLE_STORAGE_BIT = 1 << 4,
		E_GL_RUNTIME_SUPPORT_FLAG_EXPLICIT_SHADER_ATTRIBUTE_LOCATION_BIT = 1 << 0,
		E_GL_RUNTIME_SUPPORT_FLAG_EXPLICIT_SHADER_FRAG_DATA_LOCATION_BIT = 1 << 1,
		E_GL_RUNTIME_SUPPORT_FLAG_EXPLICIT_SHADER_UNIFORM_BINDING_BIT    = 1 << 2,
		E_GL_RUNTIME_SUPPORT_FLAG_SEPARATE_SHADER_STAGES_BIT             = 1 << 3,
	};

	namespace coreutil
	{

		IC3_ATTR_NO_DISCARD Bitmask<EGLRuntimeSupportFlags> queryGLRuntimeSupportFlags( const System::OpenGLVersionSupportInfo & pSupportInfo );

	}

} // namespace Ic3::Graphics::GCI

#endif // __IC3_GRAPHICS_HW3D_GLCOMMON_COMMON_DEFS_H__
