
function( ebsCoreAppend pListName pListSetCache pAppendUniqueOnly pValue )
    if( NOT pValue )
        return()
    endif()
    if( pAppendUniqueOnly )
	    foreach( valueItem ${pValue} )
		    list( APPEND ${pListName} "${valueItem}" )
	    endforeach()
    else()
        set( ${pListName} "${${pListName}};${pValue}" )
    endif()
    if( pListSetCache )
        set( ${pListName} "${${pListName}}" CACHE INTERNAL "${pListName}" )
    else()
        set( ${pListName} "${${pListName}}" PARENT_SCOPE )
    endif()
endfunction()

macro( ebsCoreAppendUniqueInternal pListName pContent )
    ebsCoreAppend( ${pListName} TRUE TRUE "${pContent}" )
endmacro()

macro( ebsClearInternalCache )
    foreach( variable ${CM_EBS_VARREG} )
        set( ${variable} "" CACHE INTERNAL "" )
    endforeach()
    set( CM_EBS_VARREG "" CACHE INTERNAL "" )
endmacro()

macro( ebsAppendInternal pListName )
    ebsCoreAppend( ${pListName} TRUE TRUE "${ARGN}" )
    ebsCoreAppend( CM_EBS_VARREG TRUE TRUE "${pListName}" )
endmacro()

macro( ebsSetInternal pVarName )
    set( ${pVarName} "${ARGN}" CACHE INTERNAL "" )
    ebsCoreAppend( CM_EBS_VARREG TRUE TRUE "${pVarName}" )
endmacro()
